//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdmin.webadmin_model.Entity
{
    using System;
    
    public partial class usp_ValidarIngresoUsuario_Result1
    {
        public string IdUsuario { get; set; }
        public string Username { get; set; }
        public Nullable<System.Guid> IdToken { get; set; }
        public string Nombre { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public string Email { get; set; }
        public System.Guid IdAplicacion { get; set; }
        public int IdEmpresa { get; set; }
    }
}
